#!/usr/bin/env python3
"""Toolchain-based export of the MLP detector to C via onnx2c.

Pipeline:
  1. PyTorch propeller_fault_mlp_keras_set05.pt
     `torch.onnx.export(model, dummy, "mlp.onnx", opset_version=13)`
       --> mlp.onnx           (open standard ML graph format)
  2. onnx2c mlp.onnx -o nn_detect_model_onnx2c.c
       --> nn_detect_model_onnx2c.c  (forward pass + weights as `static const`)
       (https://github.com/kraiskil/onnx2c, MIT license, see README)
  3. Thin C++ wrapper in nn_detect_model.cpp adapts the generated
     `void entry(const float input[1][46], float output[1][1])` to the
     NNDetectModel::predict_proba(float[46]) API used by the flight mode.

Source model: method_mlp.pkl (Pipeline = StandardScaler + sklearn.MLPClassifier
с архитектурой 46 -> 16 ReLU -> 1, выход sigmoid) обученная в ветке `tests`.
Конвертация .pkl -> .pt выполняется `export_mlp_to_cpp.py`.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from pathlib import Path

import numpy as np
import torch

from export_mlp_to_cpp import MLPDetector

THIS_DIR = Path(__file__).resolve().parent
DEFAULT_PT = THIS_DIR / "propeller_fault_mlp_keras_set05.pt"
DEFAULT_OUT = THIS_DIR.parent / "files" / "ArduCopter"

DEFAULT_ONNX2C = Path(os.environ.get(
    "ONNX2C_BIN", str(Path.home() / "onnx2c" / "build" / "onnx2c")))

DEFAULT_PROTOBUF_LIB = Path(os.environ.get("PROTOBUF_LIB_DIR", ""))


def export_to_onnx(pt_path: Path, onnx_path: Path) -> None:
    model = MLPDetector(in_features=46, hidden=16)
    state = torch.load(pt_path, map_location="cpu", weights_only=True)
    model.load_state_dict(state)
    model.eval()
   
    dummy = torch.zeros(1, 46, dtype=torch.float32)

    torch.onnx.export(
        model, dummy, str(onnx_path),
        input_names=["features"], output_names=["logit"],
        opset_version=13,
        d os.environ.copy()
    if str(DEFAULT_PROTOBUF_LIB) and DEFAULT_PROTOBUF_LIB.is_dir():
        env["LD_LIBRARY_PATH"] = (
            str(DEFAULT_PROTOBUF_LIB) + ":" + env.get("LD_LIBRARY_PATH", ""))
    print(f"$ {DEFAULT_ONNX2C} {onnx_path} > {out_c}")
    with out_c.open("w") as fp:
        fp.write("// AUTO-GENERATED by onnx2c (https://github.com/kraiskil/onnx2c, MIT).\n")
        fp.write(f"// Source ONNX: {onnx_path.name}\n")
        fp.write("// Source PyTorch: propeller_fault_mlp_keras_set05.pt (branch `tests`).\n")
        fp.write("// Built from: method_mlp.pkl (sklearn 46->16->1, StandardScaler).\n")
        fp.write("// Do not edit by hand - regenerate via model_export/export_via_onnx2c.py.\n\n")
        subprocess.run(
            [str(DEFAULT_ONNX2C), str(onnx_path)],
            stdout=fp, check=True, env=env)
    size_kb = out_c.stat().st_size / 1024.0
    n_lines = sum(1 for _ in out_c.open())
    print(f"Wrote {out_c}  ({size_kb:.1f} KB, {n_lines} lines)")


def verify_pt_onnx(pt_path: Path, onnx_path: Path, n_trials: int = 5) -> float:
    """Sanity-check that the ONNX export still agrees with PyTorch."""
    try:
        import onnxruntime as ort
    except ImportError:
        print("onnxruntime not installed - skipping ONNX vs PyTorch check.")
        return 0.0
    pt_model = MLPDetector(in_features=46, hidden=16)
    pt_model.load_state_dict(torch.load(pt_path, map_location="cpu",
                                        weights_only=True))
    pt_model.eval()
    sess = ort.InferenceSession(str(onnx_path),
                                providers=["CPUExecutionProvider"])
    rng = np.random.default_rng(0)
    max_diff = 0.0
    for _ in range(n_trials):
        x = rng.uniform(-2.0, 2.0, size=(1, 46)).astype(np.float32)
        with torch.no_grad():
            pt_logit = pt_model(torch.from_numpy(x)).item()
        pt_p = 1.0 / (1.0 + np.exp(-pt_logit))
        onnx_logit = float(sess.run(None, {"features": x})[0][0])
        onnx_p = 1.0 / (1.0 + np.exp(-onnx_logit))
        max_diff = max(max_diff, abs(pt_p - onnx_p))
    return max_diff


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pt", type=Path, default=DEFAULT_PT)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    onnx_path = THIS_DIR / "mlp.onnx"
    export_to_onnx(args.pt, onnx_path)
    diff = verify_pt_onnx(args.pt, onnx_path)
    print(f"PyTorch vs ONNX-runtime max |P_diff| = {diff:.3e}")
    assert diff < 1e-5, "ONNX export does not round-trip PyTorch"

    args.out.mkdir(parents=True, exist_ok=True)
    out_c = args.out / "nn_detect_model_onnx2c.c"
    run_onnx2c(onnx_path, out_c)


if __name__ == "__main__":
    main()
   f"onnx2c binary not found: {DEFAULT_ONNX2C}\n"
            "Build it once with the instructions in model_export/README.md, or "
            "set the ONNX2C_BIN environment variable.")
    env = os.environ.copy()
    if str(DEFAULT_PROTOBUF_LIB) and DEFAULT_PROTOBUF_LIB.is_dir():
        env["LD_LIBRARY_PATH"] = (
            str(DEFAULT_PROTOBUF_LIB) + ":" + env.get("LD_LIBRARY_PATH", ""))
    print(f"$ {DEFAULT_ONNX2C} {onnx_path} > {out_c}")
    with out_c.open("w") as fp:
        fp.write("// AUTO-GENERATED by onnx2c (https://github.com/kraiskil/onnx2c, MIT).\n")
        fp.write(f"// Source ONNX: {onnx_path.name}\n")
        fp.write("// Source PyTorch: propeller_fault_mlp_keras_set05.pt (branch `tests`).\n")
        fp.write("// Built from: method_mlp.pkl (sklearn 46->16->1, StandardScaler).\n")
        fp.write("// Do not edit by hand - regenerate via model_export/export_via_onnx2c.py.\n\n")
        subprocess.run(
            [str(DEFAULT_ONNX2C), str(onnx_path)],
            stdout=fp, check=True, env=env)
    size_kb = out_c.stat().st_size / 1024.0
    n_lines = sum(1 for _ in out_c.open())
    print(f"Wrote {out_c}  ({size_kb:.1f} KB, {n_lines} lines)")


def verify_pt_onnx(pt_path: Path, onnx_path: Path, n_trials: int = 5) -> float:
    """Sanity-check that the ONNX export still agrees with PyTorch."""
    try:
        import onnxruntime as ort
    except ImportError:
        print("onnxruntime not installed - skipping ONNX vs PyTorch check.")
        return 0.0
    pt_model = MLPDetector(in_features=46, hidden=16)
    pt_model.load_state_dict(torch.load(pt_path, map_location="cpu",
                                        weights_only=True))
    pt_model.eval()
    sess = ort.InferenceSession(str(onnx_path),
                                providers=["CPUExecutionProvider"])
    rng = np.random.default_rng(0)
    max_diff = 0.0
    for _ in range(n_trials):
        x = rng.uniform(-2.0, 2.0, size=(1, 46)).astype(np.float32)
        with torch.no_grad():
            pt_logit = pt_model(torch.from_numpy(x)).item()
        pt_p = 1.0 / (1.0 + np.exp(-pt_logit))
        onnx_logit = float(sess.run(None, {"features": x})[0][0])
        onnx_p = 1.0 / (1.0 + np.exp(-onnx_logit))
        max_diff = max(max_diff, abs(pt_p - onnx_p))
    return max_diff


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pt", type=Path, default=DEFAULT_PT)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    onnx_path = THIS_DIR / "mlp.onnx"
    export_to_onnx(args.pt, onnx_path)
    diff = verify_pt_onnx(args.pt, onnx_path)
    print(f"PyTorch vs ONNX-runtime max |P_diff| = {diff:.3e}")
    assert diff < 1e-5, "ONNX export does not round-trip PyTorch"

    args.out.mkdir(parents=True, exist_ok=True)
    out_c = args.out / "nn_detect_model_onnx2c.c"
    run_onnx2c(onnx_path, out_c)


if __name__ == "__main__":
    main()
