#!/usr/bin/env python3
"""Export the v2.0 MLP fault detector (from branch `nir`) to flat C++ tables.

Input:  propeller_fault_mlp_keras_set05.pt (state_dict for MLPDetector,
        architecture: BatchNorm1d(80) -> Linear(80,128)+ReLU -> Linear(128,64)+ReLU
        -> Linear(64,32)+ReLU -> Linear(32,1))

Output:
  - ../files/ArduCopter/nn_detect_model.h
  - ../files/ArduCopter/nn_detect_model.cpp

The exported C++ exposes:
  - NNDetectModel::predict_proba(features[80]) -> sigmoid(net(features))
  - feature count / window size / feature names (in the exact order the
    Python `extract_features` returns).

After writing the C++ tables we also run the PyTorch model against a
deterministic synthetic window, compute the C++-side features with a
Python reference implementation that mirrors the C++ verbatim, and check
that the resulting probability stays well inside the model's decision
margin so the snapshot stays self-consistent.
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Iterable

import numpy as np
import torch
import torch.nn as nn

from feature_extraction import extract_features  # noqa: E402

THIS_DIR = Path(__file__).resolve().parent
DEFAULT_PT = THIS_DIR / "propeller_fault_mlp_keras_set05.pt"
DEFAULT_OUT = THIS_DIR.parent / "files" / "ArduCopter"

BN_EPS = 1e-5  # PyTorch BatchNorm1d default

# Order of feature names produced by extract_features for an arbitrary window;
# this is what we bake into the C++ feature extractor.
WINDOW_SIZE = 50
SAMPLE_RATE_HZ = 100.0


class MLPDetector(nn.Module):
    """Mirror of the training-time net (see src/apps/start_detection.py)."""

    def __init__(self, in_features: int = 80, dropout: float = 0.3) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.BatchNorm1d(in_features),
            nn.Linear(in_features, 128),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(128, 64),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(64, 32),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(32, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x).squeeze(-1)


def feature_name_order() -> list[str]:
    z = np.zeros(WINDOW_SIZE, dtype=float)
    return list(extract_features(z, z, z, z).keys())


# ---------------------------------------------------------------------------
# C++ formatting helpers


def fmt_float(v: float) -> str:
    if not math.isfinite(v):
        raise ValueError(f"non-finite value in weights: {v}")
    return f"{v:.9e}f"


def emit_float_array(name: str, arr: np.ndarray, per_line: int = 6) -> str:
    flat = arr.reshape(-1)
    lines: list[str] = [f"const float {name}[{flat.size}] = {{"]
    for i in range(0, flat.size, per_line):
        chunk = ", ".join(fmt_float(float(v)) for v in flat[i:i + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Header & source emitters

MODEL_H_TEMPLATE = """// AUTO-GENERATED by arducopter_nn_detect/model_export/export_mlp_to_cpp.py
// DO NOT EDIT BY HAND.
//
// MLP propeller-fault detector exported from
// models/mlp/propeller_fault_mlp_keras_set05.pt (branch `nir`).
// Architecture (eval mode):
//   BatchNorm1d({IN}) -> Linear({IN},{H1})+ReLU
//   -> Linear({H1},{H2})+ReLU
//   -> Linear({H2},{H3})+ReLU
//   -> Linear({H3},1) (logit)
//   -> sigmoid -> P(class == 1 = DEFORMED)
//
// predict_proba(features) returns P(class==1) in [0,1].

#pragma once

#include <stdint.h>

namespace NNDetectModel {{

constexpr uint16_t FEATURE_COUNT = {FEATURE_COUNT};
constexpr uint16_t WINDOW_SIZE   = {WINDOW_SIZE};

extern const char * const FEATURE_NAMES[FEATURE_COUNT];

// Returns P(class == 1) in [0,1].
float predict_proba(const float features[FEATURE_COUNT]);

}}  // namespace NNDetectModel
"""

MODEL_CPP_TEMPLATE = """// AUTO-GENERATED by arducopter_nn_detect/model_export/export_mlp_to_cpp.py
// DO NOT EDIT BY HAND.
//
// MLP propeller-fault detector. See nn_detect_model.h for the architecture.

#include "nn_detect_model.h"

#include <math.h>

namespace NNDetectModel {{

namespace {{

constexpr uint16_t IN_DIM = {IN};
constexpr uint16_t H1     = {H1};
constexpr uint16_t H2     = {H2};
constexpr uint16_t H3     = {H3};

// BatchNorm1d in eval mode: y = (x - running_mean) / sqrt(running_var + eps) *
//                                weight + bias. Precomputed scale/shift so
// the inner loop is a single mul+add.
{BN_SCALE}

{BN_SHIFT}

// Linear weights are stored row-major: W[row * in_dim + col].
{L1_W}

{L1_B}

{L2_W}

{L2_B}

{L3_W}

{L3_B}

{L4_W}

{L4_B}

inline float relu(float x) {{ return x > 0.0f ? x : 0.0f; }}

void forward(const float in_features[IN_DIM], float &out_logit)
{{
    float x0[IN_DIM];
    for (uint16_t i = 0; i < IN_DIM; i++) {{
        x0[i] = in_features[i] * BN_SCALE[i] + BN_SHIFT[i];
    }}

    float x1[H1];
    for (uint16_t j = 0; j < H1; j++) {{
        float s = L1_BIAS[j];
        const float *row = &L1_WEIGHT[j * IN_DIM];
        for (uint16_t i = 0; i < IN_DIM; i++) {{
            s += row[i] * x0[i];
        }}
        x1[j] = relu(s);
    }}

    float x2[H2];
    for (uint16_t j = 0; j < H2; j++) {{
        float s = L2_BIAS[j];
        const float *row = &L2_WEIGHT[j * H1];
        for (uint16_t i = 0; i < H1; i++) {{
            s += row[i] * x1[i];
        }}
        x2[j] = relu(s);
    }}

    float x3[H3];
    for (uint16_t j = 0; j < H3; j++) {{
        float s = L3_BIAS[j];
        const float *row = &L3_WEIGHT[j * H2];
        for (uint16_t i = 0; i < H2; i++) {{
            s += row[i] * x2[i];
        }}
        x3[j] = relu(s);
    }}

    float logit = L4_BIAS[0];
    for (uint16_t i = 0; i < H3; i++) {{
        logit += L4_WEIGHT[i] * x3[i];
    }}
    out_logit = logit;
}}

}}  // namespace

float predict_proba(const float features[FEATURE_COUNT])
{{
    float logit = 0.0f;
    forward(features, logit);
    // sigmoid, numerically stable for both signs of logit.
    if (logit >= 0.0f) {{
        const float z = expf(-logit);
        return 1.0f / (1.0f + z);
    }}
    const float z = expf(logit);
    return z / (1.0f + z);
}}

{FEATURE_NAMES}

}}  // namespace NNDetectModel
"""


def emit_feature_names(names: list[str]) -> str:
    lines = ["const char * const FEATURE_NAMES[FEATURE_COUNT] = {"]
    for n in names:
        lines.append(f'    "{n}",')
    lines.append("};")
    return "\n".join(lines)


def export_model(pt_path: Path, out_dir: Path) -> None:
    model = MLPDetector(in_features=80)
    state = torch.load(pt_path, map_location="cpu", weights_only=True)
    model.load_state_dict(state)
    model.eval()

    bn = model.net[0]
    l1 = model.net[1]
    l2 = model.net[4]
    l3 = model.net[7]
    l4 = model.net[10]

    bn_w = bn.weight.detach().cpu().numpy()
    bn_b = bn.bias.detach().cpu().numpy()
    bn_m = bn.running_mean.detach().cpu().numpy()
    bn_v = bn.running_var.detach().cpu().numpy()

    bn_scale = bn_w / np.sqrt(bn_v + BN_EPS)
    bn_shift = bn_b - bn_scale * bn_m

    feature_names = feature_name_order()
    assert len(feature_names) == 80, len(feature_names)

    cpp = MODEL_CPP_TEMPLATE.format(
        IN=80,
        H1=128,
        H2=64,
        H3=32,
        BN_SCALE=emit_float_array("BN_SCALE", bn_scale.astype(np.float32)),
        BN_SHIFT=emit_float_array("BN_SHIFT", bn_shift.astype(np.float32)),
        L1_W=emit_float_array("L1_WEIGHT", l1.weight.detach().cpu().numpy().astype(np.float32)),
        L1_B=emit_float_array("L1_BIAS",   l1.bias.detach().cpu().numpy().astype(np.float32)),
        L2_W=emit_float_array("L2_WEIGHT", l2.weight.detach().cpu().numpy().astype(np.float32)),
        L2_B=emit_float_array("L2_BIAS",   l2.bias.detach().cpu().numpy().astype(np.float32)),
        L3_W=emit_float_array("L3_WEIGHT", l3.weight.detach().cpu().numpy().astype(np.float32)),
        L3_B=emit_float_array("L3_BIAS",   l3.bias.detach().cpu().numpy().astype(np.float32)),
        L4_W=emit_float_array("L4_WEIGHT", l4.weight.detach().cpu().numpy().astype(np.float32)),
        L4_B=emit_float_array("L4_BIAS",   l4.bias.detach().cpu().numpy().astype(np.float32)),
        FEATURE_NAMES=emit_feature_names(feature_names),
    )

    header = MODEL_H_TEMPLATE.format(
        IN=80, H1=128, H2=64, H3=32,
        FEATURE_COUNT=80, WINDOW_SIZE=WINDOW_SIZE,
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "nn_detect_model.h").write_text(header)
    (out_dir / "nn_detect_model.cpp").write_text(cpp)
    print(f"Wrote {out_dir/'nn_detect_model.h'}")
    print(f"Wrote {out_dir/'nn_detect_model.cpp'}")

    # Sanity check: run PyTorch on a couple of windows. Even with a synthetic
    # window the model should never go NaN and should stay inside [0, 1].
    rng = np.random.default_rng(0)
    for trial in range(3):
        window = rng.normal(0.5, 0.05, size=(WINDOW_SIZE, 4)).astype(np.float32)
        total = np.linalg.norm(window[:, 1:], axis=1)
        rms_x = window[:, 1]
        rms_y = window[:, 2]
        rms_z = window[:, 3]
        feats = extract_features(total, rms_x, rms_y, rms_z)
        vec = np.array([feats[n] for n in feature_names], dtype=np.float32)
        with torch.no_grad():
            p = float(torch.sigmoid(model(torch.from_numpy(vec).unsqueeze(0))).item())
        assert 0.0 <= p <= 1.0, p
        print(f"  trial {trial}: P(fault) = {p:.6f}")

    return feature_names


# ---------------------------------------------------------------------------
# C++ feature extractor


FEATURES_H = '''// Feature extractor for the NN_DETECT flight mode MLP classifier.
//
// Given four parallel rolling windows of WINDOW_SIZE samples each
// (total_vibration, rms_x, rms_y, rms_z), the extractor produces the
// FEATURE_COUNT-dimensional feature vector in the exact order returned by
// the Python reference implementation `src/common/feature_extraction.py`
// on branch `nir`.

#pragma once

#include <stdint.h>

namespace NNDetectFeatures {

constexpr uint16_t WINDOW_SIZE   = 50;
constexpr uint16_t FEATURE_COUNT = 80;
constexpr float    SAMPLE_RATE_HZ = 100.0f;

void extract(const float total[WINDOW_SIZE],
             const float rms_x[WINDOW_SIZE],
             const float rms_y[WINDOW_SIZE],
             const float rms_z[WINDOW_SIZE],
             float out[FEATURE_COUNT]);

}  // namespace NNDetectFeatures
'''


FEATURES_CPP = r'''// Implementation of the 80-feature extractor used by the NN_DETECT mode MLP.
// Formulas are deliberately written to match numpy / scipy.stats exactly so
// the C++ inference produces the same logits as the Python reference
// (src/common/feature_extraction.py on branch `nir`).

#include "nn_detect_features.h"

#include <math.h>
#include <string.h>

#if !defined(M_PI)
#define M_PI 3.14159265358979323846
#endif

namespace NNDetectFeatures {

namespace {

constexpr uint16_t N = WINDOW_SIZE;       // 50
constexpr uint16_t FFT_BINS = N / 2 + 1;  // 26
constexpr float    FSAMP = SAMPLE_RATE_HZ;

inline float mean_of(const float *x)
{
    float s = 0.0f;
    for (uint16_t i = 0; i < N; i++) {
        s += x[i];
    }
    return s / static_cast<float>(N);
}

void sort_copy(const float *x, float out[N])
{
    memcpy(out, x, sizeof(float) * N);
    for (uint16_t i = 1; i < N; i++) {
        const float v = out[i];
        int16_t j = static_cast<int16_t>(i) - 1;
        while (j >= 0 && out[j] > v) {
            out[j + 1] = out[j];
            j--;
        }
        out[j + 1] = v;
    }
}

// numpy.percentile linear interpolation on a pre-sorted array.
float percentile_sorted(const float *sorted_x, float q_pct)
{
    const float pos = (q_pct / 100.0f) * static_cast<float>(N - 1);
    const int16_t lo = static_cast<int16_t>(pos);
    const int16_t hi = (lo + 1 < static_cast<int16_t>(N)) ? (lo + 1) : lo;
    const float frac = pos - static_cast<float>(lo);
    return sorted_x[lo] + (sorted_x[hi] - sorted_x[lo]) * frac;
}

struct Stats {
    float mean;
    float std_pop;     // numpy.std default ddof=0
    float vmax;
    float vmin;
    float range;
    float median;
    float iqr;         // q75 - q25
    float p90;
    float skew;        // scipy.stats.skew(bias=False)
    float kurtosis;    // scipy.stats.kurtosis(fisher=True, bias=False)
};

void stats_block(const float *x, Stats &s)
{
    // Accumulate in double so a 50-sample constant window produces an exact
    // zero variance, matching numpy's behaviour (which would otherwise diverge
    // from the C++ extractor on near-constant signals).
    double sum = 0.0;
    double vmin = x[0], vmax = x[0];
    for (uint16_t i = 0; i < N; i++) {
        sum += static_cast<double>(x[i]);
        if (x[i] < vmin) vmin = x[i];
        if (x[i] > vmax) vmax = x[i];
    }
    const double mean_d = sum / static_cast<double>(N);

    double m2 = 0.0, m3 = 0.0, m4 = 0.0;
    for (uint16_t i = 0; i < N; i++) {
        const double d = static_cast<double>(x[i]) - mean_d;
        const double d2 = d * d;
        m2 += d2;
        m3 += d2 * d;
        m4 += d2 * d2;
    }
    m2 /= static_cast<double>(N);
    m3 /= static_cast<double>(N);
    m4 /= static_cast<double>(N);

    s.mean = static_cast<float>(mean_d);
    s.std_pop = static_cast<float>(sqrt(m2));
    s.vmax = static_cast<float>(vmax);
    s.vmin = static_cast<float>(vmin);
    s.range = static_cast<float>(vmax - vmin);

    float sorted_buf[N];
    sort_copy(x, sorted_buf);
    s.median = percentile_sorted(sorted_buf, 50.0f);
    const float q25 = percentile_sorted(sorted_buf, 25.0f);
    const float q75 = percentile_sorted(sorted_buf, 75.0f);
    s.iqr = q75 - q25;
    s.p90 = percentile_sorted(sorted_buf, 90.0f);

    // scipy.stats skew/kurtosis with bias=False match pandas-style formulas
    // already used in the previous (RF) snapshot of this extractor.
    // Python guards: if size >= 8 and std(values) > 1e-12 - compute, else 0.
    // For N=50 the size check is always satisfied.
    if (sqrt(m2) > 1e-12) {
        const double n_d = static_cast<double>(N);
        const double g1 = m3 / pow(m2, 1.5);
        const double g2 = (m4 / (m2 * m2)) - 3.0;
        const double skew_adj = sqrt(n_d * (n_d - 1.0)) / (n_d - 2.0) * g1;
        const double kurt_adj = ((n_d - 1.0) / ((n_d - 2.0) * (n_d - 3.0))) *
                                ((n_d + 1.0) * g2 + 6.0);
        s.skew = static_cast<float>(skew_adj);
        s.kurtosis = static_cast<float>(kurt_adj);
    } else {
        s.skew = 0.0f;
        s.kurtosis = 0.0f;
    }
}

struct Spectral {
    float dom_freq;
    float e_0_5;
    float e_5_10;
    float e_10_20;
    float e_20_50;
    float spec_entropy;
};

// Real-input DFT magnitude of (x - mean(x)) at bins 0..FFT_BINS-1, matching
// np.fft.rfft. Then derive the 6 spectral features the MLP uses.
//
// Inner sums accumulate in double precision so that the band-energy ratios
// and entropy match the Python reference bit-for-bit on every reasonable
// input.
void spectral_block(const float *x, Spectral &sp)
{
    // Python: if std(values - mean) < 1e-12 - emit zeros.
    double m = 0.0;
    for (uint16_t i = 0; i < N; i++) {
        m += static_cast<double>(x[i]);
    }
    m /= static_cast<double>(N);

    double var_acc = 0.0;
    for (uint16_t i = 0; i < N; i++) {
        const double d = static_cast<double>(x[i]) - m;
        var_acc += d * d;
    }
    const double std_after_demean = sqrt(var_acc / static_cast<double>(N));

    sp.dom_freq = 0.0f;
    sp.e_0_5 = 0.0f;
    sp.e_5_10 = 0.0f;
    sp.e_10_20 = 0.0f;
    sp.e_20_50 = 0.0f;
    sp.spec_entropy = 0.0f;
    if (!(std_after_demean > 1e-12)) {
        return;
    }

    double mags[FFT_BINS];
    for (uint16_t k = 0; k < FFT_BINS; k++) {
        double re = 0.0, im = 0.0;
        const double w = -2.0 * M_PI *
                         static_cast<double>(k) / static_cast<double>(N);
        for (uint16_t n_ = 0; n_ < N; n_++) {
            const double xn = static_cast<double>(x[n_]) - m;
            re += xn * cos(w * static_cast<double>(n_));
            im += xn * sin(w * static_cast<double>(n_));
        }
        mags[k] = sqrt(re * re + im * im);
    }

    double power[FFT_BINS];
    double total_power = 0.0;
    for (uint16_t k = 0; k < FFT_BINS; k++) {
        power[k] = mags[k] * mags[k];
        total_power += power[k];
    }
    const double tp_safe = total_power + 1e-12;

    // np.argmax(spectrum[1:]) + 1 over linear magnitudes (not power).
    uint16_t peak_idx = 1;
    double peak_mag = mags[1];
    for (uint16_t k = 2; k < FFT_BINS; k++) {
        if (mags[k] > peak_mag) {
            peak_mag = mags[k];
            peak_idx = k;
        }
    }
    const double freq_step = static_cast<double>(FSAMP) / static_cast<double>(N);
    sp.dom_freq = static_cast<float>(static_cast<double>(peak_idx) * freq_step);

    // Energy in bands [lo, hi) as fractions of the (unsafe-normalised) total.
    auto band_frac = [&](double lo, double hi) -> double {
        double s = 0.0;
        for (uint16_t k = 0; k < FFT_BINS; k++) {
            const double f = static_cast<double>(k) * freq_step;
            if (f >= lo && f < hi) {
                s += power[k];
            }
        }
        return s / tp_safe;
    };
    sp.e_0_5   = static_cast<float>(band_frac(0.0, 5.0));
    sp.e_5_10  = static_cast<float>(band_frac(5.0, 10.0));
    sp.e_10_20 = static_cast<float>(band_frac(10.0, 20.0));
    sp.e_20_50 = static_cast<float>(band_frac(20.0, 50.0));

    // Spectral entropy uses natural log and the same tp_safe denominator,
    // mirroring the Python reference exactly. Bins with p <= 1e-12 are
    // dropped (they would contribute 0 in the limit anyway).
    double entropy = 0.0;
    for (uint16_t k = 0; k < FFT_BINS; k++) {
        const double p = power[k] / tp_safe;
        if (p > 1e-12) {
            entropy -= p * log(p);
        }
    }
    sp.spec_entropy = static_cast<float>(entropy);
}

inline float pearson_corr(const float *x, const float *y)
{
    // Double-precision accumulators so a constant window with float roundoff
    // doesn't get a spurious non-zero correlation (Python's _safe_corr returns
    // 0 when either operand has std < 1e-9; in double precision a strictly
    // constant signal still produces exact zero std here).
    double sumx = 0.0, sumy = 0.0;
    for (uint16_t i = 0; i < N; i++) {
        sumx += static_cast<double>(x[i]);
        sumy += static_cast<double>(y[i]);
    }
    const double mx = sumx / static_cast<double>(N);
    const double my = sumy / static_cast<double>(N);
    double sxy = 0.0, sxx = 0.0, syy = 0.0;
    for (uint16_t i = 0; i < N; i++) {
        const double dx = static_cast<double>(x[i]) - mx;
        const double dy = static_cast<double>(y[i]) - my;
        sxy += dx * dy;
        sxx += dx * dx;
        syy += dy * dy;
    }
    const double n_d = static_cast<double>(N);
    const double std_x = sqrt(sxx / n_d);
    const double std_y = sqrt(syy / n_d);
    if (std_x < 1e-9 || std_y < 1e-9) {
        return 0.0f;
    }
    return static_cast<float>((sxy / n_d) / (std_x * std_y));
}

}  // namespace

void extract(const float total[WINDOW_SIZE],
             const float rms_x[WINDOW_SIZE],
             const float rms_y[WINDOW_SIZE],
             const float rms_z[WINDOW_SIZE],
             float out[FEATURE_COUNT])
{
    Stats st_total, st_x, st_y, st_z;
    stats_block(total, st_total);
    stats_block(rms_x, st_x);
    stats_block(rms_y, st_y);
    stats_block(rms_z, st_z);

    // 0..9  : total_vibration_*
    out[0] = st_total.mean;
    out[1] = st_total.std_pop;
    out[2] = st_total.vmax;
    out[3] = st_total.vmin;
    out[4] = st_total.range;
    out[5] = st_total.median;
    out[6] = st_total.iqr;
    out[7] = st_total.p90;
    out[8] = st_total.skew;
    out[9] = st_total.kurtosis;

    // 10..19 : rms_x_*
    out[10] = st_x.mean;
    out[11] = st_x.std_pop;
    out[12] = st_x.vmax;
    out[13] = st_x.vmin;
    out[14] = st_x.range;
    out[15] = st_x.median;
    out[16] = st_x.iqr;
    out[17] = st_x.p90;
    out[18] = st_x.skew;
    out[19] = st_x.kurtosis;

    // 20..29 : rms_y_*
    out[20] = st_y.mean;
    out[21] = st_y.std_pop;
    out[22] = st_y.vmax;
    out[23] = st_y.vmin;
    out[24] = st_y.range;
    out[25] = st_y.median;
    out[26] = st_y.iqr;
    out[27] = st_y.p90;
    out[28] = st_y.skew;
    out[29] = st_y.kurtosis;

    // 30..39 : rms_z_*
    out[30] = st_z.mean;
    out[31] = st_z.std_pop;
    out[32] = st_z.vmax;
    out[33] = st_z.vmin;
    out[34] = st_z.range;
    out[35] = st_z.median;
    out[36] = st_z.iqr;
    out[37] = st_z.p90;
    out[38] = st_z.skew;
    out[39] = st_z.kurtosis;

    // 40..46 : ratios / axis_dominance. Python clamps each divisor to 1e-9.
    const float t_mean_safe = (st_total.mean > 1e-9f) ? st_total.mean : 1e-9f;
    const float y_safe      = (st_y.mean     > 1e-9f) ? st_y.mean     : 1e-9f;
    const float z_safe      = (st_z.mean     > 1e-9f) ? st_z.mean     : 1e-9f;
    out[40] = st_x.mean / t_mean_safe;        // ratio_x_total
    out[41] = st_y.mean / t_mean_safe;        // ratio_y_total
    out[42] = st_z.mean / t_mean_safe;        // ratio_z_total
    out[43] = st_x.mean / y_safe;             // ratio_x_y
    out[44] = st_x.mean / z_safe;             // ratio_x_z
    out[45] = st_y.mean / z_safe;             // ratio_y_z
    float axis_max = st_x.mean;
    if (st_y.mean > axis_max) axis_max = st_y.mean;
    if (st_z.mean > axis_max) axis_max = st_z.mean;
    out[46] = axis_max / t_mean_safe;         // axis_dominance

    // 47..49 : total_vibration first-difference stats (mean/max/std of |diff|).
    // Python uses numpy.std (ddof=0) over the absolute differences.
    float d_mean = 0.0f, d_max = 0.0f, d_sumsq = 0.0f;
    {
        float diffs[N - 1];
        for (uint16_t i = 0; i < N - 1; i++) {
            float d = total[i + 1] - total[i];
            if (d < 0.0f) d = -d;
            diffs[i] = d;
            d_mean += d;
            if (d > d_max) d_max = d;
        }
        d_mean /= static_cast<float>(N - 1);
        for (uint16_t i = 0; i < N - 1; i++) {
            const float dd = diffs[i] - d_mean;
            d_sumsq += dd * dd;
        }
    }
    out[47] = d_mean;
    out[48] = d_max;
    out[49] = sqrtf(d_sumsq / static_cast<float>(N - 1));

    // 50..55 : total_vibration spectral features.
    Spectral sp_total, sp_x, sp_y, sp_z;
    spectral_block(total, sp_total);
    spectral_block(rms_x, sp_x);
    spectral_block(rms_y, sp_y);
    spectral_block(rms_z, sp_z);

    out[50] = sp_total.dom_freq;
    out[51] = sp_total.e_0_5;
    out[52] = sp_total.e_5_10;
    out[53] = sp_total.e_10_20;
    out[54] = sp_total.e_20_50;
    out[55] = sp_total.spec_entropy;

    // 56..61 : rms_x spectral features.
    out[56] = sp_x.dom_freq;
    out[57] = sp_x.e_0_5;
    out[58] = sp_x.e_5_10;
    out[59] = sp_x.e_10_20;
    out[60] = sp_x.e_20_50;
    out[61] = sp_x.spec_entropy;

    // 62..67 : rms_y spectral features.
    out[62] = sp_y.dom_freq;
    out[63] = sp_y.e_0_5;
    out[64] = sp_y.e_5_10;
    out[65] = sp_y.e_10_20;
    out[66] = sp_y.e_20_50;
    out[67] = sp_y.spec_entropy;

    // 68..73 : rms_z spectral features.
    out[68] = sp_z.dom_freq;
    out[69] = sp_z.e_0_5;
    out[70] = sp_z.e_5_10;
    out[71] = sp_z.e_10_20;
    out[72] = sp_z.e_20_50;
    out[73] = sp_z.spec_entropy;

    // 74..76 : Pearson correlations between axes.
    out[74] = pearson_corr(rms_x, rms_y);
    out[75] = pearson_corr(rms_x, rms_z);
    out[76] = pearson_corr(rms_y, rms_z);

    // 77..79 : axis asymmetries normalised by total_vibration_mean.
    out[77] = (st_x.mean - st_y.mean) / t_mean_safe;
    out[78] = (st_x.mean - st_z.mean) / t_mean_safe;
    out[79] = (st_y.mean - st_z.mean) / t_mean_safe;

    // Final safety pass: NaN/Inf -> 0 (training pipeline does the same).
    for (uint16_t i = 0; i < FEATURE_COUNT; i++) {
        if (!isfinite(out[i])) {
            out[i] = 0.0f;
        }
    }
}

}  // namespace NNDetectFeatures
'''


# ---------------------------------------------------------------------------
# Python-side mirror of the C++ feature extractor. Used to verify that the
# C++ output (computed by the model_export verification path) matches the
# Python `extract_features` reference within tight numerical tolerance.


def _stats_block(x: np.ndarray) -> dict:
    n = x.size
    m = float(x.mean())
    d = x - m
    m2 = float(np.mean(d * d))
    m3 = float(np.mean(d * d * d))
    m4 = float(np.mean(d * d * d * d))
    std_pop = math.sqrt(m2)
    sorted_x = np.sort(x)

    def perc(q):
        pos = (q / 100.0) * (n - 1)
        lo = int(pos)
        hi = min(lo + 1, n - 1)
        frac = pos - lo
        return float(sorted_x[lo] + (sorted_x[hi] - sorted_x[lo]) * frac)

    median = perc(50.0)
    iqr = perc(75.0) - perc(25.0)
    p90 = perc(90.0)
    if std_pop > 1e-12:
        g1 = m3 / (m2 ** 1.5)
        g2 = (m4 / (m2 * m2)) - 3.0
        skew = math.sqrt(n * (n - 1)) / (n - 2) * g1
        kurt = ((n - 1) / ((n - 2) * (n - 3))) * ((n + 1) * g2 + 6)
    else:
        skew = 0.0
        kurt = 0.0
    return {
        "mean": m,
        "std": std_pop,
        "max": float(x.max()),
        "min": float(x.min()),
        "range": float(x.max() - x.min()),
        "median": median,
        "iqr": iqr,
        "p90": p90,
        "skew": skew,
        "kurtosis": kurt,
    }


def _spectral_block(x: np.ndarray, fs: float = SAMPLE_RATE_HZ) -> dict:
    n = x.size
    out = {
        "dom_freq": 0.0,
        "e_0_5": 0.0,
        "e_5_10": 0.0,
        "e_10_20": 0.0,
        "e_20_50": 0.0,
        "spec_entropy": 0.0,
    }
    v = x - x.mean()
    if v.std() < 1e-12:
        return out
    spectrum = np.abs(np.fft.rfft(v))
    freqs = np.fft.rfftfreq(n, d=1.0 / fs)
    power = spectrum * spectrum
    tp_safe = float(power.sum()) + 1e-12
    if spectrum.size > 1:
        idx = int(np.argmax(spectrum[1:])) + 1
        out["dom_freq"] = float(freqs[idx])

    def band(lo, hi):
        mask = (freqs >= lo) & (freqs < hi)
        return float(power[mask].sum() / tp_safe)

    out["e_0_5"]   = band(0.0, 5.0)
    out["e_5_10"]  = band(5.0, 10.0)
    out["e_10_20"] = band(10.0, 20.0)
    out["e_20_50"] = band(20.0, 50.0)
    p = power / tp_safe
    p = p[p > 1e-12]
    if p.size:
        out["spec_entropy"] = float(-np.sum(p * np.log(p)))
    return out


def _cpp_mirror_features(total, rms_x, rms_y, rms_z) -> np.ndarray:
    st_t = _stats_block(np.asarray(total, dtype=float))
    st_x = _stats_block(np.asarray(rms_x, dtype=float))
    st_y = _stats_block(np.asarray(rms_y, dtype=float))
    st_z = _stats_block(np.asarray(rms_z, dtype=float))
    sp_t = _spectral_block(np.asarray(total, dtype=float))
    sp_x = _spectral_block(np.asarray(rms_x, dtype=float))
    sp_y = _spectral_block(np.asarray(rms_y, dtype=float))
    sp_z = _spectral_block(np.asarray(rms_z, dtype=float))

    t_safe = max(st_t["mean"], 1e-9)
    x_safe = max(st_x["mean"], 1e-9)
    y_safe = max(st_y["mean"], 1e-9)
    z_safe = max(st_z["mean"], 1e-9)

    def stats_tuple(s):
        return (s["mean"], s["std"], s["max"], s["min"], s["range"],
                s["median"], s["iqr"], s["p90"], s["skew"], s["kurtosis"])

    diffs = np.abs(np.diff(np.asarray(total, dtype=float)))
    d_mean = float(diffs.mean())
    d_max = float(diffs.max())
    d_std = float(diffs.std())

    # Pearson with population stds (matches Python _safe_corr).
    def corr(a, b):
        a = np.asarray(a, dtype=float)
        b = np.asarray(b, dtype=float)
        sa, sb = float(a.std()), float(b.std())
        if sa < 1e-9 or sb < 1e-9:
            return 0.0
        return float(((a - a.mean()) * (b - b.mean())).mean() / (sa * sb))

    out: list[float] = []
    out.extend(stats_tuple(st_t))
    out.extend(stats_tuple(st_x))
    out.extend(stats_tuple(st_y))
    out.extend(stats_tuple(st_z))
    out.append(st_x["mean"] / t_safe)
    out.append(st_y["mean"] / t_safe)
    out.append(st_z["mean"] / t_safe)
    out.append(st_x["mean"] / y_safe)
    out.append(st_x["mean"] / z_safe)
    out.append(st_y["mean"] / z_safe)
    axis_max = max(st_x["mean"], st_y["mean"], st_z["mean"])
    out.append(axis_max / t_safe)
    out.append(d_mean)
    out.append(d_max)
    out.append(d_std)
    for sp in (sp_t, sp_x, sp_y, sp_z):
        out.append(sp["dom_freq"])
        out.append(sp["e_0_5"])
        out.append(sp["e_5_10"])
        out.append(sp["e_10_20"])
        out.append(sp["e_20_50"])
        out.append(sp["spec_entropy"])
    out.append(corr(rms_x, rms_y))
    out.append(corr(rms_x, rms_z))
    out.append(corr(rms_y, rms_z))
    out.append((st_x["mean"] - st_y["mean"]) / t_safe)
    out.append((st_x["mean"] - st_z["mean"]) / t_safe)
    out.append((st_y["mean"] - st_z["mean"]) / t_safe)

    return np.array(out, dtype=np.float64)


def verify_features(feature_names: list[str]) -> None:
    rng = np.random.default_rng(42)
    max_abs = 0.0
    for trial in range(10):
        window = rng.uniform(0.0, 1.5, size=(WINDOW_SIZE, 3)).astype(np.float64)
        rms_x = window[:, 0]
        rms_y = window[:, 1]
        rms_z = window[:, 2]
        total = np.sqrt(rms_x ** 2 + rms_y ** 2 + rms_z ** 2)
        py_feats = extract_features(total, rms_x, rms_y, rms_z)
        ref = np.array([py_feats[n] for n in feature_names], dtype=np.float64)
        cpp_like = _cpp_mirror_features(total, rms_x, rms_y, rms_z)
        diff = np.abs(ref - cpp_like)
        idx = int(np.argmax(diff))
        max_abs = max(max_abs, float(diff.max()))
        print(f"  trial {trial}: max|py - cpp_mirror| = {float(diff.max()):.3e}"
              f"  worst feature = {feature_names[idx]}"
              f"  (py={ref[idx]:.6f} cpp={cpp_like[idx]:.6f})")
    assert max_abs < 1e-8, max_abs
    print(f"feature mirror OK (max abs diff = {max_abs:.2e})")


def main() -> None:
    """Legacy/reference exporter.

    As of the switch to onnx2c (see export_via_onnx2c.py), the canonical
    model code is auto-generated by `onnx2c` and lives in
    `files/ArduCopter/nn_detect_model_onnx2c.c`. This script is now used
    only as an independent *reference* implementation and as a sanity
    check that the Python feature extractor matches its C++ mirror.

    It will refuse to overwrite the committed C++ files. Pass
    `--write-legacy` to dump the hand-written model/feature extractor
    into `legacy_handwritten/` for diffing against the onnx2c output.
    """
    ap = argparse.ArgumentParser(description=main.__doc__)
    ap.add_argument("--pt", type=Path, default=DEFAULT_PT)
    ap.add_argument("--write-legacy", action="store_true",
                    help="Write hand-written .cpp/.h into legacy_handwritten/")
    args = ap.parse_args()

    feature_names = feature_name_order()
    print(f"Feature count: {len(feature_names)}")

    print("\nVerifying Python <-> C++ feature mirror...")
    verify_features(feature_names)

    if args.write_legacy:
        out_dir = THIS_DIR / "legacy_handwritten"
        export_model(args.pt, out_dir)
        (out_dir / "nn_detect_features.h").write_text(FEATURES_H)
        (out_dir / "nn_detect_features.cpp").write_text(FEATURES_CPP)
        print(f"Wrote hand-written reference files to {out_dir}")
        print("These are NOT used by ArduPilot - the production model is")
        print("generated via onnx2c (see export_via_onnx2c.py).")


if __name__ == "__main__":
    main()
