#!/usr/bin/env python3
"""Compile the C++ extractor + MLP and check it matches PyTorch.

Usage:
    python3 verify_against_cpp.py [--csv path/to/vibration_log.csv]

Without --csv we feed a few deterministic synthetic windows. The script
exits non-zero if either:
  - the C++ feature vector deviates from the Python `extract_features` by
    more than 1e-4 on any feature; or
  - the C++ probability deviates from the PyTorch MLP by more than 1e-4.
"""
from __future__ import annotations

import argparse
import io
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from feature_extraction import extract_features
from export_mlp_to_cpp import MLPDetector, feature_name_order

THIS_DIR = Path(__file__).resolve().parent
CPP_FILES = [
    THIS_DIR.parent / "files" / "ArduCopter" / "nn_detect_features.cpp",
    THIS_DIR.parent / "files" / "ArduCopter" / "nn_detect_model.cpp",
    # Auto-generated by onnx2c, compiled as C and linked with the C++ wrapper.
    THIS_DIR.parent / "files" / "ArduCopter" / "nn_detect_model_onnx2c.c",
    THIS_DIR / "cpp_test_harness.cpp",
]
BIN = THIS_DIR / "cpp_test_harness.bin"
WINDOW_SIZE = 50


def compile_cpp() -> Path:
    cxx = shutil.which("g++") or shutil.which("clang++")
    cc = shutil.which("gcc") or shutil.which("clang")
    if cxx is None or cc is None:
        raise SystemExit("No C/C++ compiler found.")
    # The onnx2c-generated file is C (with C linkage for `entry`), so we
    # compile it separately with the C compiler before linking with g++.
    # ArduPilot's waf build system makes the same per-extension distinction.
    c_files = [p for p in CPP_FILES if p.suffix == ".c"]
    cpp_files = [p for p in CPP_FILES if p.suffix != ".c"]
    objs: list[Path] = []
    for cfile in c_files:
        obj = cfile.with_suffix(".o")
        cmd_c = [cc, "-std=c11", "-O2", "-Wall", "-c", str(cfile), "-o", str(obj)]
        print("$", " ".join(cmd_c))
        subprocess.check_call(cmd_c)
        objs.append(obj)
    cmd = [cxx, "-std=c++14", "-O2", "-Wall", "-o", str(BIN)]
    cmd += [str(p) for p in cpp_files] + [str(o) for o in objs]
    print("$", " ".join(cmd))
    subprocess.check_call(cmd)
    return BIN


def run_cpp(total, x, y, z) -> tuple[np.ndarray, float]:
    buf = io.StringIO()
    for i in range(WINDOW_SIZE):
        buf.write(f"{float(total[i]):.9f} {float(x[i]):.9f} "
                  f"{float(y[i]):.9f} {float(z[i]):.9f}\n")
    res = subprocess.run([str(BIN)], input=buf.getvalue(), capture_output=True,
                         text=True, check=True)
    feats: list[float] = []
    proba: float = -1.0
    for line in res.stdout.splitlines():
        if line.startswith("FEATURES"):
            feats = [float(v) for v in line.split()[1:]]
        elif line.startswith("PROBA"):
            proba = float(line.split()[1])
    assert len(feats) == 80, len(feats)
    assert 0.0 <= proba <= 1.0, proba
    return np.array(feats, dtype=np.float64), proba


def load_pytorch_model() -> MLPDetector:
    model = MLPDetector(in_features=80)
    state = torch.load(THIS_DIR / "propeller_fault_mlp_keras_set05.pt",
                       map_location="cpu", weights_only=True)
    model.load_state_dict(state)
    model.eval()
    return model


def torch_proba(model: MLPDetector, feature_names: list[str], feats: dict) -> float:
    vec = np.array([feats[n] for n in feature_names], dtype=np.float32)
    with torch.no_grad():
        return float(torch.sigmoid(model(torch.from_numpy(vec).unsqueeze(0))).item())


def synthetic_windows(seed: int = 0) -> list[tuple[np.ndarray, ...]]:
    rng = np.random.default_rng(seed)
    out = []
    for _ in range(4):
        rms = rng.uniform(0.0, 1.5, size=(WINDOW_SIZE, 3))
        total = np.sqrt((rms ** 2).sum(axis=1))
        out.append((total, rms[:, 0], rms[:, 1], rms[:, 2]))
    # Add one near-constant window to exercise the spectral-zero guard.
    const = np.full((WINDOW_SIZE,), 0.42, dtype=np.float64)
    out.append((const.copy(), const.copy(), const.copy(), const.copy()))
    return out


def csv_windows(path: Path) -> list[tuple[np.ndarray, ...]]:
    df = pd.read_csv(path)
    cols = ["total_vibration", "rms_x", "rms_y", "rms_z"]
    if not set(cols).issubset(df.columns):
        raise SystemExit(f"CSV missing required columns: {cols} (have {list(df.columns)})")
    total = df["total_vibration"].to_numpy(dtype=float)
    x = df["rms_x"].to_numpy(dtype=float)
    y = df["rms_y"].to_numpy(dtype=float)
    z = df["rms_z"].to_numpy(dtype=float)
    out = []
    step = max(1, (len(df) - WINDOW_SIZE) // 5)
    for start in range(0, len(df) - WINDOW_SIZE + 1, step):
        sl = slice(start, start + WINDOW_SIZE)
        out.append((total[sl], x[sl], y[sl], z[sl]))
        if len(out) >= 5:
            break
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", type=Path, default=None,
                    help="Real vibration_log.csv to slice into windows.")
    args = ap.parse_args()

    compile_cpp()
    model = load_pytorch_model()
    feature_names = feature_name_order()

    windows = csv_windows(args.csv) if args.csv else synthetic_windows()
    max_feat_diff = 0.0
    max_proba_diff = 0.0

    for idx, (total, x, y, z) in enumerate(windows):
        feats_py = extract_features(np.asarray(total, float),
                                    np.asarray(x, float),
                                    np.asarray(y, float),
                                    np.asarray(z, float))
        ref = np.array([feats_py[n] for n in feature_names], dtype=np.float64)
        cpp_feats, cpp_p = run_cpp(total, x, y, z)
        py_p = torch_proba(model, feature_names, feats_py)
        diff = np.abs(ref - cpp_feats)
        worst = int(np.argmax(diff))
        print(f"window {idx}: "
              f"max|feat py-cpp|={float(diff.max()):.3e} "
              f"(worst: {feature_names[worst]} py={ref[worst]:+.6f} "
              f"cpp={cpp_feats[worst]:+.6f}), "
              f"P(fault) py={py_p:.6f} cpp={cpp_p:.6f} "
              f"(|Δ|={abs(py_p - cpp_p):.3e})")
        max_feat_diff = max(max_feat_diff, float(diff.max()))
        max_proba_diff = max(max_proba_diff, abs(py_p - cpp_p))

    print()
    print(f"max feature diff: {max_feat_diff:.3e}")
    print(f"max P(fault) diff: {max_proba_diff:.3e}")
    if max_feat_diff > 1e-4 or max_proba_diff > 1e-4:
        print("MISMATCH - tolerance exceeded.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
