// Thin C++ facade over the onnx2c-generated forward pass.
//
// onnx2c emits a pure C function with the signature
//
//   void entry(const float input[1][80], float output[1]);
//
// This file:
//   1) declares that function in the extern "C" namespace,
//   2) applies a numerically stable sigmoid to its output,
//   3) exposes the result via NNDetectModel::predict_proba(),
//   4) carries the feature-name table consumed by debugging tooling.
//
// The feature-name list is the exact key order returned by the Python
// reference src/common/feature_extraction.py on branch `nir`. It is
// kept in C++ rather than in the auto-generated .c so that regenerating
// the model via onnx2c does not stomp on the names.

#include "nn_detect_model.h"

#include <math.h>

extern "C" {
// Defined in nn_detect_model_onnx2c.c (auto-generated by onnx2c).
void entry(const float tensor_features[1][80], float tensor_logit[1]);
}

namespace NNDetectModel {

float predict_proba(const float features[FEATURE_COUNT])
{
    float input[1][80];
    for (uint16_t i = 0; i < FEATURE_COUNT; i++) {
        input[0][i] = features[i];
    }
    float logit[1] = { 0.0f };
    entry(input, logit);

    // Numerically stable sigmoid.
    const float z = logit[0];
    if (z >= 0.0f) {
        return 1.0f / (1.0f + expf(-z));
    }
    const float ez = expf(z);
    return ez / (1.0f + ez);
}

const char * const FEATURE_NAMES[FEATURE_COUNT] = {
    "total_vibration_mean",
    "total_vibration_std",
    "total_vibration_max",
    "total_vibration_min",
    "total_vibration_range",
    "total_vibration_median",
    "total_vibration_iqr",
    "total_vibration_p90",
    "total_vibration_skew",
    "total_vibration_kurtosis",
    "rms_x_mean",
    "rms_x_std",
    "rms_x_max",
    "rms_x_min",
    "rms_x_range",
    "rms_x_median",
    "rms_x_iqr",
    "rms_x_p90",
    "rms_x_skew",
    "rms_x_kurtosis",
    "rms_y_mean",
    "rms_y_std",
    "rms_y_max",
    "rms_y_min",
    "rms_y_range",
    "rms_y_median",
    "rms_y_iqr",
    "rms_y_p90",
    "rms_y_skew",
    "rms_y_kurtosis",
    "rms_z_mean",
    "rms_z_std",
    "rms_z_max",
    "rms_z_min",
    "rms_z_range",
    "rms_z_median",
    "rms_z_iqr",
    "rms_z_p90",
    "rms_z_skew",
    "rms_z_kurtosis",
    "ratio_x_total",
    "ratio_y_total",
    "ratio_z_total",
    "ratio_x_y",
    "ratio_x_z",
    "ratio_y_z",
    "axis_dominance",
    "total_vibration_diff_mean",
    "total_vibration_diff_max",
    "total_vibration_diff_std",
    "total_vibration_dom_freq",
    "total_vibration_e_0_5",
    "total_vibration_e_5_10",
    "total_vibration_e_10_20",
    "total_vibration_e_20_50",
    "total_vibration_spec_entropy",
    "rms_x_dom_freq",
    "rms_x_e_0_5",
    "rms_x_e_5_10",
    "rms_x_e_10_20",
    "rms_x_e_20_50",
    "rms_x_spec_entropy",
    "rms_y_dom_freq",
    "rms_y_e_0_5",
    "rms_y_e_5_10",
    "rms_y_e_10_20",
    "rms_y_e_20_50",
    "rms_y_spec_entropy",
    "rms_z_dom_freq",
    "rms_z_e_0_5",
    "rms_z_e_5_10",
    "rms_z_e_10_20",
    "rms_z_e_20_50",
    "rms_z_spec_entropy",
    "corr_xy",
    "corr_xz",
    "corr_yz",
    "asym_xy",
    "asym_xz",
    "asym_yz",
};

}  // namespace NNDetectModel
