// Thin C++ facade over the onnx2c-generated forward pass.
//
// onnx2c emits a pure C function with the signature
//
//   void entry(const float input[1][46], float output[1]);
//
// This file:
//   1) declares that function in the extern "C" namespace,
//   2) applies a numerically stable sigmoid to its output,
//   3) exposes the result via NNDetectModel::predict_proba(),
//   4) carries the feature-name table consumed by debugging tooling.
//
// The feature-name list is the exact key order returned by the Python
// reference features.extract_features on branch `tests`. It is
// kept in C++ rather than in the auto-generated .c so that regenerating
// the model via onnx2c does not stomp on the names.

#include "nn_detect_model.h"

#include <math.h>

extern "C" {
// Defined in nn_detect_model_onnx2c.c (auto-generated by onnx2c).
void entry(const float tensor_features[1][46], float tensor_logit[1]);
}

namespace NNDetectModel {

float predict_proba(const float features[FEATURE_COUNT])
{
    float input[1][46];
    for (uint16_t i = 0; i < FEATURE_COUNT; i++) {
        input[0][i] = features[i];
    }
    float logit[1] = { 0.0f };
    entry(input, logit);

    // Numerically stable sigmoid.
    const float z = logit[0];
    if (z >= 0.0f) {
        return 1.0f / (1.0f + expf(-z));
    }
    const float ez = expf(z);
    return ez / (1.0f + ez);
}

const char * const FEATURE_NAMES[FEATURE_COUNT] = {
    "total_mean",
    "total_std",
    "total_max",
    "total_min",
    "total_p95",
    "total_range",
    "rms_x_mean",
    "rms_x_std",
    "rms_x_max",
    "rms_x_min",
    "rms_x_p95",
    "rms_x_range",
    "rms_y_mean",
    "rms_y_std",
    "rms_y_max",
    "rms_y_min",
    "rms_y_p95",
    "rms_y_range",
    "rms_z_mean",
    "rms_z_std",
    "rms_z_max",
    "rms_z_min",
    "rms_z_p95",
    "rms_z_range",
    "spec_total_band_0_10",
    "spec_total_band_10_20",
    "spec_total_band_20_35",
    "spec_total_band_35_50",
    "spec_x_band_0_10",
    "spec_x_band_10_20",
    "spec_x_band_20_35",
    "spec_x_band_35_50",
    "spec_y_band_0_10",
    "spec_y_band_10_20",
    "spec_y_band_20_35",
    "spec_y_band_35_50",
    "spec_z_band_0_10",
    "spec_z_band_10_20",
    "spec_z_band_20_35",
    "spec_z_band_35_50",
    "corr_x_y",
    "corr_x_z",
    "corr_y_z",
    "corr_total_x",
    "corr_total_y",
    "corr_total_z",
};

}  // namespace NNDetectModel
