// Thin facade over the onnx2c-generated MLP forward pass.
//
// The actual model — weights + node functions — lives in
// nn_detect_model_onnx2c.c, which was auto-generated by
//   onnx2c (https://github.com/kraiskil/onnx2c, MIT license)
// from the ONNX export of the v2.0 PyTorch propeller-fault MLP
// (models/mlp/propeller_fault_mlp_keras_set05.pt on branch `nir`).
// Regenerate via arducopter_nn_detect/model_export/export_via_onnx2c.py.
//
// Architecture (eval mode, after BatchNorm folding done by ONNX export):
//   BatchNorm1d(80) -> Linear(80,128)+ReLU
//                   -> Linear(128,64)+ReLU
//                   -> Linear(64,32)+ReLU
//                   -> Linear(32,1)  (logit)
//   -> sigmoid (applied by predict_proba) -> P(class == 1 = DEFORMED)

#pragma once

#include <stdint.h>

namespace NNDetectModel {

constexpr uint16_t FEATURE_COUNT = 80;
constexpr uint16_t WINDOW_SIZE   = 50;

extern const char * const FEATURE_NAMES[FEATURE_COUNT];

// Returns P(class == 1) in [0,1].
float predict_proba(const float features[FEATURE_COUNT]);

}  // namespace NNDetectModel
