// Thin facade over the onnx2c-generated MLP forward pass.
//
// The actual model — weights + node functions — lives in
// nn_detect_model_onnx2c.c, which was auto-generated by
//   onnx2c (https://github.com/kraiskil/onnx2c, MIT license)
// from the ONNX export of the PyTorch mirror of the v3 MLP detector
// (method_mlp.pkl in branch `tests`).
// Regenerate via arducopter_nn_detect/model_export/export_via_onnx2c.py.
//
// Architecture (eval mode):
//   BatchNorm1d(46, affine=false)  // запекает StandardScaler из Pipeline
//     -> Linear(46, 16) + ReLU
//     -> Linear(16, 1)              // logit
//   -> sigmoid (applied by predict_proba) -> P(class == 1 = DEFORMED)

#pragma once

#include <stdint.h>

namespace NNDetectModel {

constexpr uint16_t FEATURE_COUNT = 46;
constexpr uint16_t WINDOW_SIZE   = 10;

extern const char * const FEATURE_NAMES[FEATURE_COUNT];

// Returns P(class == 1) in [0,1].
float predict_proba(const float features[FEATURE_COUNT]);

}  // namespace NNDetectModel
