// AUTO-GENERATED by methods/export_rf_to_cpp.py - DO NOT EDIT BY HAND.
//
// Random Forest exported from propeller_fault_rf.pkl
//   trees           : 200
//   nodes (total)   : 79348
//   feature count   : 73
//   window size     : 50
//   class labels    : 0 = NORMAL, 1 = DEFORMED
//
// predict_proba(features) returns the mean probability of class 1
// (propeller deformed) across all trees, computed by traversing every
// tree from its root and averaging the per-leaf class-1 ratio.

#pragma once

#include <stdint.h>

namespace NNDetectModel {

constexpr uint16_t FEATURE_COUNT = 73;
constexpr uint16_t WINDOW_SIZE   = 50;
constexpr uint16_t TREE_COUNT    = 200;
constexpr uint32_t TOTAL_NODES   = 79348;

struct Node {
    int16_t feature;   // index into features[]; -1 marks a leaf
    int16_t left;      // tree-local child index (0-based within tree)
    int16_t right;
    float   threshold; // split value (ignored for leaves)
    float   value;     // probability of class 1 (only meaningful at leaves)
};

extern const Node     NODES[TOTAL_NODES];
extern const uint32_t TREE_OFFSETS[TREE_COUNT + 1];

extern const char * const FEATURE_NAMES[FEATURE_COUNT];

// Returns P(class == 1) in [0,1].
float predict_proba(const float features[FEATURE_COUNT]);

}  // namespace NNDetectModel
